export { ExtensionHost, extensionHost } from "./extensionHost";
export type {
	ContributedCursorStyle,
	ContributedFrame,
	ContributedSound,
	ContributedWallpaper,
	ContributedWebcamFrame,
	CursorEffectContext,
	CursorEffectFn,
	ExtensionContributions,
	ExtensionEvent,
	ExtensionEventType,
	ExtensionInfo,
	ExtensionManifest,
	ExtensionPermission,
	ExtensionSettingField,
	ExtensionSettingsPanel,
	ExtensionStatus,
	FrameInstance,
	GlitchRecordExtensionAPI,
	GlitchRecordExtensionModule,
	RenderHookContext,
	RenderHookFn,
	RenderHookPhase,
} from "./types";
